version: '3.3'
services:
  resilio:
    image: ghcr.io/linuxserver/resilio-sync
    container_name: resilio
    volumes:
      - ./resilio/config:/config
      - ./resilio/downloads:/downloads
      - /srv/docker_data/sync:/sync
    ports:
      - 55555:55555
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resilio.rule=Host(`resilio.${DOMAIN}`)"
      - "traefik.http.routers.resilio.entrypoints=websecure"
      - "traefik.http.routers.resilio.tls.certresolver=mytlschallenge"
      - "traefik.http.services.resilio.loadbalancer.server.port=8888"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
