version: '3.3'

services:
  frontend:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Frontend
      - "traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=mytlschallenge"
      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.${DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=mytlschallenge"
    restart: unless-stopped

networks:
  proxy:
    external: true